#Various chest protections
break-protection: true
hopper-protection: true
explosion-protection: true

max-distance-lock: 4
#All editable messages of the plugin
message:
  msg1: "&cYou cannot break this chest because it does not belong to you!"
  msg2: "&cYou cannot place the chest here!"
  msg3: "&cYou do not have access to this chest! It belongs to %player%"
  msg4: "&aYou have granted %player% permission to use the chest"
  msg5: "&cYou have run out of available slots!"
  msg6: "&aPlayer %player% has been removed!"
  msg7: "&aThe chest has been locked!"
  msg8: "&aThe chest has been unlocked!"
  msg9: "&cYou cannot place a hopper under a protected chest!"
  msg10: "&cYou do not have permission for this!"
  msg11: "&cThis chest does not belong to you!"
  msg12: "&eYou did not enter the player's name!\n&eUse: /lock add | remove <player>"
  msg13: "&cYou cannot unlock other players' chests!"
  msg14: "&eThis chest is not locked!"

info:
  msg1: "&6===== SmartChestLock ====="
  msg2: "&fPlayers assigned:"
  msg3: "&e> "
  msg4: "&6========================"


