#Various chest protections
break-protection: true
hopper-protection: true
explosion-protection: true

max-distance-lock: 4
#All editable messages of the plugin
message:
  msg1: "&cNon puoi rompere questa chest perchè non ti appartiene!"
  msg2: "&cNon puoi piazzare la chest qui!"
  msg3: "&cNon hai accesso a questa chest! Appartiene a %player%"
  msg4: "&aHai dato il permesso a %player% di usare la chest"
  msg5: "&cHai terminato gli slot disponibili!"
  msg6: "&aIl giocatore %player% è stato rimosso!"
  msg7: "&aLa chest è stata bloccata!"
  msg8: "&aLa chest è stata sbloccata!"
  msg9: "&cNon puoi piazzare una tramoggia sotto una chest protetta!"
  msg10: "&CNon hai il permesso per questo!"
  msg11: "&cQuesta chest non ti appartiene!"
  msg12: "&eNon hai inserito il nome del giocatore!\n&eUsa: /lock add | remove <player>"
  msg13: "&cNon puoi sbloccare chest di altri giocatori!"
  msg14: "&eQuesta chest non è bloccata!"

